data_source snowflake_sample_data:
  type: snowflake
  connection:
    username: pravash02
    password: Prav@041193
    account: vrcleuv-ie46785
    database: SNOWFLAKE_SAMPLE_DATA
    warehouse: PRAY_TEST
    connection_timeout: 300
    role: ACCOUNTADMIN
    client_session_keep_alive:
    session_parameters:
      QUERY_TAG: soda-queries
      QUOTED_IDENTIFIERS_IGNORE_CASE: false
  schema: TPCH_SF100

# soda scan -d snowflake_sample_data -c configuration.yml checks.yml
